basket/urls.py
from django.urls import path
from setuptools.extern import names

from core.url import app_name
from . import views
app_name = 'basket'
urlpatterns = [
    path('',views.basket_general,name='basket_general'),
    path('add_dish/',views.basket_add,name='basket_add'),
    path('delete_dish/',views.basket_delete,name='basket_delete'),
    path('update_dish/',views.basket_update,name='basket_update'),
]

begin/urls.py
from core.views import index
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
#from core.views import DishListView,DishDetailView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.url',namespace='core')),
    #path('dish_expand/<int:dish_pk>', include('core.url',namespace='core'), name="dish_expand"),
    #path('',DishListView.as_view(),name="index"),
    path('about/',include('core.url',namespace='core')),
    path('dish/',include('core.url',namespace='core')),
    path("add_dish/",include("core.url",namespace='core')),
    path("search/",include("core.url",namespace='core')),
    path('basket/',include('basket.urls',namespace='basket')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

basket/models.py
from django.db import models

# Create your models here.

core/models.py
from enum import unique

from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
class DishManager(models.Manager):
    def get_queryset(self):
        return super(DishManager, self).get_queryset().filter(in_stock=True)

class Category(models.Model):
    objects = None
    category_name = models.CharField(max_length=30,null=False,blank=False,db_index=True)
    slug = models.SlugField(max_length=255,null=True,unique=True)

    def get_absolute_url(self):
        return reverse('core:category_set', args=[self.slug])
    def __str__(self):
        return self.category_name
    class Meta:
        db_table = "categories"
        verbose_name_plural = "Categories"

class Dish(models.Model):
    dish_name = models.CharField(verbose_name="Meal",max_length=255,null=False,blank=False)
    dish_description = models.TextField(blank=True)
    dish_image = models.ImageField(upload_to="images/",null=True)
    spice_level = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    has_chestnuts = models.BooleanField(default=False,null=False,blank=False)
    is_vegetarian = models.BooleanField(default=False,null=False,blank=False)
    price = models.DecimalField(validators=[MinValueValidator(0)],max_digits=5,default=9999,decimal_places=2)
    in_stock = models.BooleanField(default=True,null=False)
    slug = models.SlugField(max_length=255,null=True,unique=True)
    dishes = DishManager()
    dish_category = models.ForeignKey("core.Category",related_name='dish',on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.dish_name

    def get_absolute_url(self):
        return reverse('core:dish_expand',args=[self.slug])

    class Meta:
        db_table = "dishes"
        verbose_name_plural = "Dishes"

core/forms.py
from django import forms

from .models import Dish

class DishForms(forms.ModelForm):

    class Meta:
        model = Dish
        fields = "__all__"

basket/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from basket.basket import Basket
from core.models import Dish


# Create your views here.
def basket_general(request):
    return render(request,'basket/general.html')

def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        dish_id = int(request.POST.get('dishid'))
        dish_qty = int(request.POST.get('dishqty'))
        dish = get_object_or_404(Dish,id=dish_id)
        basketqty = basket.__len__()
        basket.add_dish(dish=dish,dish_qty=dish_qty)
        response = JsonResponse({'qty': basketqty})
        return response

def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'delete':
        dish_id = int(request.POST.get('dishid'))
        basket.delete(dish=dish_id)
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty,'subtotal': baskettotal})
        return response

def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'update':
        dish_id = int(request.POST.get('dishid'))
        dish_qty = int(request.POST.get('dishqty'))
        basket.update(dish=dish_id,qty=dish_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty,'subtotal': baskettotal})
        return response

core/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from unicodedata import category

from core.models import Dish,Category
from .forms import DishForms
# Create your views here.

def index(request):
    search_query = request.GET.get('q','')
    category = request.GET.get('category','')
    spice_level = request.GET.get('spice_level','')
    has_chestnuts = request.GET.get('has_chestnuts','')
    is_vegetarian = request.GET.get('is_vegetarian','')
    dishes = Dish.dishes.all().select_related('dish_category')
    if search_query:
        dishes = dishes.filter(Q(dish_name__icontains=search_query))
    if category:
        dishes = dishes.filter(dish_category_id=category)
    if spice_level:
        dishes = dishes.filter(spice_level=spice_level)
    if has_chestnuts:
        dishes = dishes.filter(has_chestnuts=has_chestnuts)
    if is_vegetarian:
        dishes = dishes.filter(is_vegetarian=is_vegetarian)
    categories = Category.objects.all()
    return render(request,'index.html',{
        "dishes": dishes,
        'categories': categories,
        'search_query': search_query,
        'category': category,
        'spice_level': spice_level,
        'has_chestnuts': has_chestnuts,
        'is_vegetarian': is_vegetarian,
    })
#class DishListView(ListView):
#    model = Dish
#    template_name = ("index.html")


def about(request):

    return render(request,'about.html')

def dish_expand(request,slug):

   dish_detail = get_object_or_404(Dish,slug=slug,in_stock=True)
   return render(request,'dish_expand.html',{"dish_detail": dish_detail})
#class DishDetailView(DetailView):
#   model = Dish
#    template_name = "dish_expand.html"
def category_set(request,category_slug = None):
    category = get_object_or_404(Category, slug=category_slug)
    dish_list = Dish.objects.filter(dish_category=category)
    return render(request,'category_set.html',{"category": category,"dish_list": dish_list})

def add_dish(request):

    if request.method == "POST":
        form = DishForms(request.POST)

        if form.is_valid():
            form.save()
            return redirect("core:index")
    else:
        form = DishForms()

    return render(request,"add_dish.html",{"form" : form})

core/templates/about.html
{% load static %}
<!doctype html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body>
    <header style="position: sticky; top: 0;z-index: 999;">
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">StepFoodStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <a type="button" role="button" href="{% url 'basket:basket_general' %}" class="btn btn-outline-secondary">
                        {% with total_qty=basket|length %}
                            <div id="basket-qty" class="d-inline-flex">
                                 {% if total_qty > 0 %}
                                     {{ total_qty }}
                                 {% else %}
                                     0
                                 {% endif %}
                            </div>
                        {% endwith %}
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        Basket
                    </a>
                    <form class="d-flex" action="{% url 'core:index' %}">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ search_query }}">

                        {% if category %}
                            <input type="hidden" name='category' value="{{category}}">
                        {% endif %}
                        {% if spice_level %}
                            <input type="hidden" name="spice_level" value="{{spice_level}}">
                        {% endif %}
                        {% if has_chestnuts %}
                            <input type="hidden" name="has_chestnuts" value="{{has_chestnuts}}">
                        {% endif %}
                        {% if is_vegetarian %}
                            <input type="hidden" name="is_vegetarian" value="{{is_vegetarian}}">
                        {% endif %}

                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                    <div class="text-justify">
                        <h6 style="padding-left: 350px">It's nice to see you here. Enjoy your stay :)</h6>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
    <footer style="background-color: #deded5;bottom: 0;margin-top:100px;position: relative;bottom: 0;">
    <div class="container p-4">
      <div class="row">
        <div class="col-lg-6 col-md-12 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: #818963;">footer content</h5>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
            molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
            voluptatem veniam, est atque cumque eum delectus sint!
          </p>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: #818963;">links</h5>
          <ul class="list-unstyled mb-0">
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">Frequently Asked Questions</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">Delivery</a>
            </li>
            <li class="mb-1">
              <a href="#!" style="color: #4f4f4f;">Pricing</a>
            </li>
            <li>
              <a href="#!" style="color: #4f4f4f;">Where we deliver?</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-1" style="letter-spacing: 2px; color: #818963;">opening hours</h5>
          <table class="table" style="color: #4f4f4f; border-color: #666;">
            <tbody>
              <tr>
                <td>Mon - Fri:</td>
                <td>8am - 9pm</td>
              </tr>
              <tr>
                <td>Sat - Sun:</td>
                <td>8am - 1am</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2025 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">Credit to:</a>
    </div>
  </footer>
</body>
</html>

core/templates/add_dish.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add a car</title>
  </head>
  <body>
    <main>
        <form action="." method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Add dish</button>
        </form>
    </main>
  </body>
</html>

core/templates/category_set.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About Page</title>
  </head>
  <body>
    <main>
        {% for dish in dish_list %}
        <h5>{{ dish.dish_name }}</h5>
        {% endfor %}
    </main>
  </body>
</html>

core/templates/dish_expand.html
{% extends "./about.html" %}
{% load static %}
{% block title %}
{{ dish_detail.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first">
                <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{ dish_detail.dish_image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ dish_detail.title }}</h1>
                <p>Category: <span class="lead"> {{ dish_detail.dish_category }}</span></p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6 text-end"><span class="h4 fw-bold">Price:  ${{ dish_detail.price }}</span></div>
                        </div>
                    </div>
                    <div class="col border-bottom row p-3">
                        <dt class="col-sm-3 text-truncate">Description</dt>
                        <dd class="col-sm-9">{{dish_detail.dish_description|slice:":355"}}...</dd>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
<button type="button" id="add-to-basket" value="{{dish_detail.id}}" class="btn btn-secondary btn-sm">Add to basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

<script>
    $(document).on('click', '#add-to-basket', function (act) {
        act.preventDefault();
        console.log($('#select option:selected').text());
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
               dishid: $('#add-to-basket').val(),
               dishqty: $('#select option:selected').text(),
               csrfmiddlewaretoken: "{{csrf_token}}",
               action: 'post'
        },
        success: function (json) {
        console.log(json)
           document.getElementById("basket-qty").innerHTML = json.qty
        },
        error: function (xhr,errmsg,err) {}
        });
    })
</script>

{% endblock %}

core/templates/index.html
{% extends "./about.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

  <section class="py-5 text-center" style="background-color: coral;background-size:2000px 400px;  position: relative;text-align: center;color: white;">
    <img src="media/images/site-bannered.jpeg" alt="Restaurant banner" style="border: 5px solid #555;">
    <div class="row py-lg-5" style="position: absolute;top: 50%;left: 50%;transform: translate(-50%, -50%);">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="h1 fw-bold" style="color:black;padding-right:350px">Search,Choose,Buy</h1>
        <p class="lead text-muted">This is certainly a site</p>
        <p>
          <a href="https://ge.itstep.org/" class="btn btn-primary my-2">Site made thanks to:</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <form action="" class="row g-3">
        <span class="col-auto table-info d-flex flex-row mb-3" style="width: 80%;">
          <select name="category" class="form-select w-100 border border-warning-subtle"  aria-label="Default select example">
          <option value="">All Categories</option>
          {% for cat in categories %}
              <option value="{{cat.id}}" {% if category == cat.id|stringformat:"s" %}selected{% endif %}>
                  {{ cat }}
              </option>
          {% endfor %}
          </select>
          <select name="spice_level" class="form-select w-100 min-w-min border border-warning-subtle" aria-label="Default select example">
            <option value="">Spice level</option>
            <option value="0">0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
          </select>
          <select name="has_chestnuts" class="form-select w-150 min-w-min fluid-container position-relative border border-warning-subtle" aria-label="Default select example">
            <option value="">Has chestnuts?</option>
            <option value="True">Yes</option>
            <option value="False">No</option>
          </select>
          <select name="is_vegetarian" class="form-select w-150 min-w-min border border-warning-subtle" aria-label="Default select example">
            <option value="">Is vegetarian?</option>
            <option value="False">No</option>
            <option value="True">Yes</option>
          </select>
          {% if search_query %}
             <input type="hidden" name='q' value="{{search_query}}">
          {% endif %}
        </span>
        <span class="col-auto">
          <button type="submit" class="btn btn-outline-info">Filter</button>
        </span>
      </form>
      <div class="pb-3 h5">All Dishes</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for dish in dishes %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ dish.dish_image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ dish.get_absolute_url }}">{{ dish.dish_name }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted"></small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/basket/general.html
{% extends "../about.html" %}
{% load static %}
{% block title %}Basket{% endblock %}
{% block content %}

<main class="pt-5">
  <div class="container" style="min-height:250px;">
    <h1 class="h5">Shopping basket</h1>
    {% for item in basket %}
    {% with dish=item.dish %}
    <div data-index="{{dish.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first">
        <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{ dish.dish_image.url }}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{{ dish.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2" style="color:black;">{{ dish.dish_name }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Price(One order):</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">${{ dish.price }}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select{{dish.id}}">Qty</label>
                <select id="select{{dish.id}}">
                  <option selected>
                    {{item.qty}}
                  </option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <button type="button" id="update-button" data-index="{{dish.id}}"
                  class="btn btn-outline-secondary btn-sm update-button">
                  Update
                </button>
                <button type="button" id="delete-button" data-index="{{dish.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button">
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: $<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div></div>
    </div>
  </div>
</main>

<script>
  // Delete Item
  $(document).on('click', '#delete-button', function (act) {
    act.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_delete" %}',
      data: {
        dishid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'delete'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  $(document).on('click', '#update-button', function (act) {
    act.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_update" %}',
      data: {
        dishid: $(this).data('index'),
        dishqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'update'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("subtotal").innerHTML = json.subtotal;
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}